# GET https://naja7t-server.onrender.com/api/purchase/test

# POST https://naja7t-server.onrender.com/api/purchase/checkout
# Content-Type: application/json

# {
#   "courseId": "01m308pzk5cgr6wfm9synfbf7v",
#   "fullName": "محمد الأمين",
#   "email": "student@example.com",
#   "paymentMethod": "EDAHABIA"
# }

GET https://naja7t-server.onrender.com/api/products
Content-Type: application/json